### ISSUE TITLE
Deploy site

### ISSUE THREAD

**Issue by jayascript** [jayascript/jayascript-blog#4]
GH pages is currently taken with jayascript.github.io, I don't want to pull this down until I have the content transferred over... but I don't wanna wait to deploy either!!

**Comment by mirrorquill** [comment]
From @GPT-4o:

Both **Netlify** and **Vercel** work well with **Astro**, but their ease of use and features differ slightly. Here’s a quick comparison to help you decide:

### **Netlify**
- **Ease of Use:** 
  - Very easy to set up with Astro. It supports continuous deployment, meaning every time you push to GitHub, it will automatically deploy.
  - Netlify has a built-in CDN, forms, and analytics, which can be helpful for many projects.
- **Astro Setup:**
  - You can deploy Astro with minimal configuration. Netlify even provides an official [Astro + Netlify guide](https://docs.astro.build/en/guides/deploy/netlify/) to make it seamless.
- **Additional Benefits:**
  - Free tier with 100GB/month bandwidth.
  - Built-in deploy previews, which allow you to see the results of pull requests before merging.

### **Vercel**
- **Ease of Use:**
  - Vercel is designed for frontend frameworks like Astro, so it’s very easy to deploy. Like Netlify, it supports automatic deployment via GitHub integration.
  - Vercel also offers a smooth build and deploy process with its zero-configuration deployments.
- **Astro Setup:**
  - The official [Astro + Vercel guide](https://docs.astro.build/en/guides/deploy/vercel/) makes deployment very straightforward.
- **Additional Benefits:**
  - Free tier with unlimited serverless function invocations and generous bandwidth.
  - Optimized for frontend frameworks like Next.js, Astro, etc.
  - Blazing fast with a global CDN.

### **Recommendation:**
Both platforms are great, but **Netlify** tends to offer a more straightforward experience with additional features like built-in form handling and simpler setup for static sites. **Vercel** might be better if you want optimized deployment with strong performance for frontend-heavy apps.

If you’re just looking for the **easiest deployment experience for Astro**, both will work seamlessly, so it may come down to personal preference. If you want to try something different from Heroku, I’d recommend **Netlify** for its slightly better static site features.

**Comment by mirrorquill** [comment]
Ok this was actually super easy:

https://docs.astro.build/en/guides/deploy/netlify/

Took like 3 minutes.
